// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tp_hospital.Data;

#nullable disable

namespace tp_hospital.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260303142447_AddHeadDoctorToSeed")]
    partial class AddHeadDoctorToSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("tp_hospital.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId", "DoctorId", "AppointmentDate")
                        .IsUnique();

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 2, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            Notes = "Bilan cardiaque annuel, RAS.",
                            PatientId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Notes = "Consultation fievre.",
                            PatientId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 3, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            Notes = "Suivi pediatrique.",
                            PatientId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 3, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Notes = "Controle tension arterielle.",
                            PatientId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadDoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeadDoctorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeadDoctorId = 1,
                            Name = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            HeadDoctorId = 2,
                            Name = "Urgences"
                        },
                        new
                        {
                            Id = 3,
                            HeadDoctorId = 3,
                            Name = "Pediatrie"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Sophie",
                            LastName = "Martin",
                            LicenseNumber = "LIC-0001",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Lucas",
                            LastName = "Bernard",
                            LicenseNumber = "LIC-0002",
                            Specialty = "Medecine generale"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FirstName = "Emma",
                            LastName = "Dubois",
                            LicenseNumber = "LIC-0003",
                            Specialty = "Pediatrie"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FolderNumber")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 rue de la Paix, Paris",
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jean.dupont@email.com",
                            FirstName = "Jean",
                            FolderNumber = 1001,
                            LastName = "Dupont"
                        },
                        new
                        {
                            Id = 2,
                            Address = "3 avenue des Sciences, Lyon",
                            DateOfBirth = new DateTime(1990, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.curie@email.com",
                            FirstName = "Marie",
                            FolderNumber = 1002,
                            LastName = "Curie"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 boulevard Victor Hugo, Marseille",
                            DateOfBirth = new DateTime(2000, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thomas.leroy@email.com",
                            FirstName = "Thomas",
                            FolderNumber = 1003,
                            LastName = "Leroy"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Consultation", b =>
                {
                    b.HasOne("tp_hospital.Models.Doctor", "Doctor")
                        .WithMany("Consultations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tp_hospital.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.HasOne("tp_hospital.Models.Doctor", "HeadDoctor")
                        .WithMany()
                        .HasForeignKey("HeadDoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HeadDoctor");
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.HasOne("tp_hospital.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
