// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tp_hospital.Data;

#nullable disable

namespace tp_hospital.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260305090822_AddPhoneNumber")]
    partial class AddPhoneNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("tp_hospital.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "AppointmentDate");

                    b.HasIndex("PatientId", "DoctorId", "AppointmentDate")
                        .IsUnique();

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 2, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            Notes = "Bilan cardiaque annuel, RAS.",
                            PatientId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Notes = "Consultation fievre.",
                            PatientId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 3, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            Notes = "Suivi pediatrique.",
                            PatientId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 3, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Notes = "Controle tension arterielle.",
                            PatientId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadDoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeadDoctorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeadDoctorId = 1,
                            Name = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            HeadDoctorId = 2,
                            Name = "Urgences"
                        },
                        new
                        {
                            Id = 3,
                            HeadDoctorId = 3,
                            Name = "Pediatrie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cardiologie adulte",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cardiologie pediatrique",
                            ParentDepartmentId = 1
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Sophie",
                            LastName = "Martin",
                            LicenseNumber = "LIC-0001",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Lucas",
                            LastName = "Bernard",
                            LicenseNumber = "LIC-0002",
                            Specialty = "Medecine generale"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FirstName = "Emma",
                            LastName = "Dubois",
                            LicenseNumber = "LIC-0003",
                            Specialty = "Pediatrie"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            FirstName = "Paul",
                            LastName = "Lefebvre",
                            LicenseNumber = "LIC-0004",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            FirstName = "Julie",
                            LastName = "Moreau",
                            LicenseNumber = "LIC-0005",
                            Specialty = "Urgences"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            FirstName = "Antoine",
                            LastName = "Girard",
                            LicenseNumber = "LIC-0006",
                            Specialty = "Pediatrie"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            FirstName = "Camille",
                            LastName = "Laurent",
                            LicenseNumber = "LIC-0007",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            FirstName = "Maxime",
                            LastName = "Fontaine",
                            LicenseNumber = "LIC-0008",
                            Specialty = "Urgences"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 3,
                            FirstName = "Isabelle",
                            LastName = "Roux",
                            LicenseNumber = "LIC-0009",
                            Specialty = "Pediatrie"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 1,
                            FirstName = "Nicolas",
                            LastName = "Mercier",
                            LicenseNumber = "LIC-0010",
                            Specialty = "Cardiologie"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.MedicalStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MedicalStaff");

                    b.HasDiscriminator<string>("StaffType").HasValue("MedicalStaff");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FolderNumber")
                        .IsUnique();

                    b.HasIndex("LastName");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jean.dupont@email.com",
                            FirstName = "Jean",
                            FolderNumber = 1001,
                            LastName = "Dupont",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1990, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.curie@email.com",
                            FirstName = "Marie",
                            FolderNumber = 1002,
                            LastName = "Curie",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thomas.leroy@email.com",
                            FirstName = "Thomas",
                            FolderNumber = 1003,
                            LastName = "Leroy",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1978, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.bernot@email.com",
                            FirstName = "Alice",
                            FolderNumber = 1004,
                            LastName = "Bernot",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1965, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pierre.faure@email.com",
                            FirstName = "Pierre",
                            FolderNumber = 1005,
                            LastName = "Faure",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1995, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucie.garnier@email.com",
                            FirstName = "Lucie",
                            FolderNumber = 1006,
                            LastName = "Garnier",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1982, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marc.simon@email.com",
                            FirstName = "Marc",
                            FolderNumber = 1007,
                            LastName = "Simon",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1971, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabelle.henry@email.com",
                            FirstName = "Isabelle",
                            FolderNumber = 1008,
                            LastName = "Henry",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2003, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.blanc@email.com",
                            FirstName = "David",
                            FolderNumber = 1009,
                            LastName = "Blanc",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1988, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "catherine.richard@email.com",
                            FirstName = "Catherine",
                            FolderNumber = 1010,
                            LastName = "Richard",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1993, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nicolas.lambert@email.com",
                            FirstName = "Nicolas",
                            FolderNumber = 1011,
                            LastName = "Lambert",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1979, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophie.dumont@email.com",
                            FirstName = "Sophie",
                            FolderNumber = 1012,
                            LastName = "Dumont",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(2008, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julien.dupuis@email.com",
                            FirstName = "Julien",
                            FolderNumber = 1013,
                            LastName = "Dupuis",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1960, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "claire.bertrand@email.com",
                            FirstName = "Claire",
                            FolderNumber = 1014,
                            LastName = "Bertrand",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1975, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "antoine.morin@email.com",
                            FirstName = "Antoine",
                            FolderNumber = 1015,
                            LastName = "Morin",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1998, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marine.rousseau@email.com",
                            FirstName = "Marine",
                            FolderNumber = 1016,
                            LastName = "Rousseau",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1956, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "francois.legrand@email.com",
                            FirstName = "Francois",
                            FolderNumber = 1017,
                            LastName = "Legrand",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.petit@email.com",
                            FirstName = "Laura",
                            FolderNumber = 1018,
                            LastName = "Petit",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1987, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "romain.chevalier@email.com",
                            FirstName = "Romain",
                            FolderNumber = 1019,
                            LastName = "Chevalier",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1992, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nadia.bonnet@email.com",
                            FirstName = "Nadia",
                            FolderNumber = 1020,
                            LastName = "Bonnet",
                            RowVersion = 0u
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.AdministrativeStaff", b =>
                {
                    b.HasBaseType("tp_hospital.Models.MedicalStaff");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            FirstName = "Nathalie",
                            HireDate = new DateTime(2017, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Petit",
                            Salary = 2200m,
                            Function = "Secretaire medicale"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.MedicalDoctor", b =>
                {
                    b.HasBaseType("tp_hospital.Models.MedicalStaff");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sophie",
                            HireDate = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            Salary = 6500m,
                            LicenseNumber = "EMP-0001",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Lucas",
                            HireDate = new DateTime(2018, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bernard",
                            Salary = 6200m,
                            LicenseNumber = "EMP-0002",
                            Specialty = "Medecine generale"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Emma",
                            HireDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dubois",
                            Salary = 6300m,
                            LicenseNumber = "EMP-0003",
                            Specialty = "Pediatrie"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Paul",
                            HireDate = new DateTime(2016, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lefebvre",
                            Salary = 6400m,
                            LicenseNumber = "EMP-0004",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Julie",
                            HireDate = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moreau",
                            Salary = 6100m,
                            LicenseNumber = "EMP-0005",
                            Specialty = "Urgences"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Antoine",
                            HireDate = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Girard",
                            Salary = 6000m,
                            LicenseNumber = "EMP-0006",
                            Specialty = "Pediatrie"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Camille",
                            HireDate = new DateTime(2017, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Laurent",
                            Salary = 6350m,
                            LicenseNumber = "EMP-0007",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Maxime",
                            HireDate = new DateTime(2022, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Fontaine",
                            Salary = 5900m,
                            LicenseNumber = "EMP-0008",
                            Specialty = "Urgences"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Isabelle",
                            HireDate = new DateTime(2019, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roux",
                            Salary = 6150m,
                            LicenseNumber = "EMP-0009",
                            Specialty = "Pediatrie"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Nicolas",
                            HireDate = new DateTime(2014, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mercier",
                            Salary = 6700m,
                            LicenseNumber = "EMP-0010",
                            Specialty = "Cardiologie"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Nurse", b =>
                {
                    b.HasBaseType("tp_hospital.Models.MedicalStaff");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Nurse");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            FirstName = "Claire",
                            HireDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morel",
                            Salary = 2800m,
                            Grade = "IDE",
                            Service = "Cardiologie"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Pierre",
                            HireDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Renard",
                            Salary = 3100m,
                            Grade = "IADE",
                            Service = "Urgences"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Consultation", b =>
                {
                    b.HasOne("tp_hospital.Models.Doctor", "Doctor")
                        .WithMany("Consultations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tp_hospital.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.HasOne("tp_hospital.Models.Doctor", "HeadDoctor")
                        .WithMany()
                        .HasForeignKey("HeadDoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tp_hospital.Models.Department", "ParentDepartment")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("tp_hospital.Models.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<int>("DepartmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_Street");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");

                            b1.HasData(
                                new
                                {
                                    DepartmentId = 1,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75001",
                                    Street = "1 rue du Coeur"
                                },
                                new
                                {
                                    DepartmentId = 2,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75002",
                                    Street = "2 avenue des Urgences"
                                },
                                new
                                {
                                    DepartmentId = 3,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75003",
                                    Street = "3 rue des Enfants"
                                },
                                new
                                {
                                    DepartmentId = 4,
                                    City = "",
                                    Country = "France",
                                    PostalCode = "",
                                    Street = ""
                                },
                                new
                                {
                                    DepartmentId = 5,
                                    City = "",
                                    Country = "France",
                                    PostalCode = "",
                                    Street = ""
                                });
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("HeadDoctor");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.HasOne("tp_hospital.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.OwnsOne("tp_hospital.Models.Address", "Address", b1 =>
                        {
                            b1.Property<int>("PatientId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Street");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");

                            b1.HasData(
                                new
                                {
                                    PatientId = 1,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75001",
                                    Street = "12 rue de la Paix"
                                },
                                new
                                {
                                    PatientId = 2,
                                    City = "Lyon",
                                    Country = "France",
                                    PostalCode = "69001",
                                    Street = "3 avenue des Sciences"
                                },
                                new
                                {
                                    PatientId = 3,
                                    City = "Marseille",
                                    Country = "France",
                                    PostalCode = "13001",
                                    Street = "8 boulevard Victor Hugo"
                                },
                                new
                                {
                                    PatientId = 4,
                                    City = "Bordeaux",
                                    Country = "France",
                                    PostalCode = "33000",
                                    Street = "5 rue des Lilas"
                                },
                                new
                                {
                                    PatientId = 5,
                                    City = "Toulouse",
                                    Country = "France",
                                    PostalCode = "31000",
                                    Street = "22 avenue Foch"
                                },
                                new
                                {
                                    PatientId = 6,
                                    City = "Lille",
                                    Country = "France",
                                    PostalCode = "59000",
                                    Street = "14 rue Nationale"
                                },
                                new
                                {
                                    PatientId = 7,
                                    City = "Nantes",
                                    Country = "France",
                                    PostalCode = "44000",
                                    Street = "7 impasse des Roses"
                                },
                                new
                                {
                                    PatientId = 8,
                                    City = "Strasbourg",
                                    Country = "France",
                                    PostalCode = "67000",
                                    Street = "30 rue du Moulin"
                                },
                                new
                                {
                                    PatientId = 9,
                                    City = "Montpellier",
                                    Country = "France",
                                    PostalCode = "34000",
                                    Street = "18 chemin des Vignes"
                                },
                                new
                                {
                                    PatientId = 10,
                                    City = "Rennes",
                                    Country = "France",
                                    PostalCode = "35000",
                                    Street = "2 place de la Republique"
                                },
                                new
                                {
                                    PatientId = 11,
                                    City = "Nice",
                                    Country = "France",
                                    PostalCode = "06000",
                                    Street = "9 rue Saint-Jacques"
                                },
                                new
                                {
                                    PatientId = 12,
                                    City = "Grenoble",
                                    Country = "France",
                                    PostalCode = "38000",
                                    Street = "45 boulevard Gambetta"
                                },
                                new
                                {
                                    PatientId = 13,
                                    City = "Dijon",
                                    Country = "France",
                                    PostalCode = "21000",
                                    Street = "3 allee des Peupliers"
                                },
                                new
                                {
                                    PatientId = 14,
                                    City = "Reims",
                                    Country = "France",
                                    PostalCode = "51100",
                                    Street = "11 rue du Four"
                                },
                                new
                                {
                                    PatientId = 15,
                                    City = "Clermont-Fd",
                                    Country = "France",
                                    PostalCode = "63000",
                                    Street = "60 avenue Jean Jaures"
                                },
                                new
                                {
                                    PatientId = 16,
                                    City = "Rouen",
                                    Country = "France",
                                    PostalCode = "76000",
                                    Street = "28 rue des Capucines"
                                },
                                new
                                {
                                    PatientId = 17,
                                    City = "Toulouse",
                                    Country = "France",
                                    PostalCode = "31000",
                                    Street = "6 place du Capitole"
                                },
                                new
                                {
                                    PatientId = 18,
                                    City = "Metz",
                                    Country = "France",
                                    PostalCode = "57000",
                                    Street = "15 rue Pasteur"
                                },
                                new
                                {
                                    PatientId = 19,
                                    City = "Tours",
                                    Country = "France",
                                    PostalCode = "37000",
                                    Street = "33 avenue de la Gare"
                                },
                                new
                                {
                                    PatientId = 20,
                                    City = "Caen",
                                    Country = "France",
                                    PostalCode = "14000",
                                    Street = "8 rue des Hirondelles"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("SubDepartments");
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
