// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tp_hospital.Data;

#nullable disable

namespace tp_hospital.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260303161034_AdvancedModeling")]
    partial class AdvancedModeling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("tp_hospital.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId", "DoctorId", "AppointmentDate")
                        .IsUnique();

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 2, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            Notes = "Bilan cardiaque annuel, RAS.",
                            PatientId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Notes = "Consultation fievre.",
                            PatientId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 3, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            Notes = "Suivi pediatrique.",
                            PatientId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 3, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Notes = "Controle tension arterielle.",
                            PatientId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadDoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeadDoctorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeadDoctorId = 1,
                            Name = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            HeadDoctorId = 2,
                            Name = "Urgences"
                        },
                        new
                        {
                            Id = 3,
                            HeadDoctorId = 3,
                            Name = "Pediatrie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cardiologie adulte",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cardiologie pediatrique",
                            ParentDepartmentId = 1
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Sophie",
                            LastName = "Martin",
                            LicenseNumber = "LIC-0001",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Lucas",
                            LastName = "Bernard",
                            LicenseNumber = "LIC-0002",
                            Specialty = "Medecine generale"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FirstName = "Emma",
                            LastName = "Dubois",
                            LicenseNumber = "LIC-0003",
                            Specialty = "Pediatrie"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.MedicalStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MedicalStaff");

                    b.HasDiscriminator<string>("StaffType").HasValue("MedicalStaff");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FolderNumber")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jean.dupont@email.com",
                            FirstName = "Jean",
                            FolderNumber = 1001,
                            LastName = "Dupont"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1990, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.curie@email.com",
                            FirstName = "Marie",
                            FolderNumber = 1002,
                            LastName = "Curie"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thomas.leroy@email.com",
                            FirstName = "Thomas",
                            FolderNumber = 1003,
                            LastName = "Leroy"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.AdministrativeStaff", b =>
                {
                    b.HasBaseType("tp_hospital.Models.MedicalStaff");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            FirstName = "Nathalie",
                            HireDate = new DateTime(2017, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Petit",
                            Salary = 2200m,
                            Function = "Secretaire medicale"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.MedicalDoctor", b =>
                {
                    b.HasBaseType("tp_hospital.Models.MedicalStaff");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sophie",
                            HireDate = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            Salary = 6500m,
                            LicenseNumber = "EMP-0001",
                            Specialty = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Lucas",
                            HireDate = new DateTime(2018, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bernard",
                            Salary = 6200m,
                            LicenseNumber = "EMP-0002",
                            Specialty = "Medecine generale"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Emma",
                            HireDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dubois",
                            Salary = 6300m,
                            LicenseNumber = "EMP-0003",
                            Specialty = "Pediatrie"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Nurse", b =>
                {
                    b.HasBaseType("tp_hospital.Models.MedicalStaff");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Nurse");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            FirstName = "Claire",
                            HireDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morel",
                            Salary = 2800m,
                            Grade = "IDE",
                            Service = "Cardiologie"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Pierre",
                            HireDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Renard",
                            Salary = 3100m,
                            Grade = "IADE",
                            Service = "Urgences"
                        });
                });

            modelBuilder.Entity("tp_hospital.Models.Consultation", b =>
                {
                    b.HasOne("tp_hospital.Models.Doctor", "Doctor")
                        .WithMany("Consultations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tp_hospital.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.HasOne("tp_hospital.Models.Doctor", "HeadDoctor")
                        .WithMany()
                        .HasForeignKey("HeadDoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tp_hospital.Models.Department", "ParentDepartment")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("tp_hospital.Models.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<int>("DepartmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactAddress_Street");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");

                            b1.HasData(
                                new
                                {
                                    DepartmentId = 1,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75001",
                                    Street = "1 rue du Coeur"
                                },
                                new
                                {
                                    DepartmentId = 2,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75002",
                                    Street = "2 avenue des Urgences"
                                },
                                new
                                {
                                    DepartmentId = 3,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75003",
                                    Street = "3 rue des Enfants"
                                },
                                new
                                {
                                    DepartmentId = 4,
                                    City = "",
                                    Country = "France",
                                    PostalCode = "",
                                    Street = ""
                                },
                                new
                                {
                                    DepartmentId = 5,
                                    City = "",
                                    Country = "France",
                                    PostalCode = "",
                                    Street = ""
                                });
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("HeadDoctor");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.HasOne("tp_hospital.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.OwnsOne("tp_hospital.Models.Address", "Address", b1 =>
                        {
                            b1.Property<int>("PatientId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Street");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");

                            b1.HasData(
                                new
                                {
                                    PatientId = 1,
                                    City = "Paris",
                                    Country = "France",
                                    PostalCode = "75001",
                                    Street = "12 rue de la Paix"
                                },
                                new
                                {
                                    PatientId = 2,
                                    City = "Lyon",
                                    Country = "France",
                                    PostalCode = "69001",
                                    Street = "3 avenue des Sciences"
                                },
                                new
                                {
                                    PatientId = 3,
                                    City = "Marseille",
                                    Country = "France",
                                    PostalCode = "13001",
                                    Street = "8 boulevard Victor Hugo"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("tp_hospital.Models.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("SubDepartments");
                });

            modelBuilder.Entity("tp_hospital.Models.Doctor", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("tp_hospital.Models.Patient", b =>
                {
                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
